export type Horoscope = 'Aries' | 'Taurus' | 'Gemini' | 'Cancer' | 'Leo' | 'Virgo' | 'Libra' | 'Scorpio' | 'Sagittarius' | 'Capricorn' | 'Aquarius' | 'Pisces';

export interface BirthdayData {
  month: number;
  day: number;
  horoscope: Horoscope;
  colorName: string;
  hex: string;
  meaning: string;
}

// Fungsi untuk menentukan Zodiak jika data spesifik belum ada di database
export const getZodiacSign = (day: number, month: number): Horoscope => {
  if ((month == 1 && day <= 20) || (month == 12 && day >= 22)) return 'Capricorn';
  if ((month == 1 && day >= 21) || (month == 2 && day <= 18)) return 'Aquarius';
  if ((month == 2 && day >= 19) || (month == 3 && day <= 20)) return 'Pisces';
  if ((month == 3 && day >= 21) || (month == 4 && day <= 19)) return 'Aries';
  if ((month == 4 && day >= 20) || (month == 5 && day <= 20)) return 'Taurus';
  if ((month == 5 && day >= 21) || (month == 6 && day <= 20)) return 'Gemini';
  if ((month == 6 && day >= 21) || (month == 7 && day <= 22)) return 'Cancer';
  if ((month == 7 && day >= 23) || (month == 8 && day <= 22)) return 'Leo';
  if ((month == 8 && day >= 23) || (month == 9 && day <= 22)) return 'Virgo';
  if ((month == 9 && day >= 23) || (month == 10 && day <= 22)) return 'Libra';
  if ((month == 10 && day >= 23) || (month == 11 && day <= 21)) return 'Scorpio';
  return 'Sagittarius';
};

export const birthdayColors = [
  // JANUARI (Capricorn & Aquarius) - Elemen Tanah & Udara (Warna solid, dingin, stabil)
  { month: 1, day: 1, horoscope: 'Capricorn', colorName: 'Pure White', hex: '#FFFFFF', meaning: 'Kesucian dan awal yang baru.' },
  { month: 1, day: 2, horoscope: 'Capricorn', colorName: 'Frosty White', hex: '#F0F8FF', meaning: 'Ketenangan jiwa dan pikiran jernih.' },
  { month: 1, day: 3, horoscope: 'Capricorn', colorName: 'Silver Gray', hex: '#C0C0C0', meaning: 'Kedewasaan dan intuisi tajam.' },
  { month: 1, day: 4, horoscope: 'Capricorn', colorName: 'Aluminum Gray', hex: '#A9A9A9', meaning: 'Kekuatan dan ketahanan fondasi.' },
  { month: 1, day: 5, horoscope: 'Capricorn', colorName: 'Steel Gray', hex: '#778899', meaning: 'Ketegasan dan fokus pada tujuan.' },
  { month: 1, day: 6, horoscope: 'Capricorn', colorName: 'Grape Mouse', hex: '#5C4033', meaning: 'Ketekunan dan hasil yang matang.' },
  { month: 1, day: 7, horoscope: 'Capricorn', colorName: 'Jet Black', hex: '#0A0A0A', meaning: 'Misteri dan perlindungan energi.' },
  { month: 1, day: 8, horoscope: 'Capricorn', colorName: 'Lemonade Yellow', hex: '#FDFD96', meaning: 'Harapan di tengah struktur yang kaku.' },
  { month: 1, day: 9, horoscope: 'Capricorn', colorName: 'Moss Green', hex: '#8A9A5B', meaning: 'Pertumbuhan perlahan tapi pasti.' },
  { month: 1, day: 10, horoscope: 'Capricorn', colorName: 'Grass Green', hex: '#7CFC00', meaning: 'Kehidupan dan dedikasi konstan.' },
  { month: 1, day: 11, horoscope: 'Capricorn', colorName: 'Mist Green', hex: '#C1D5C0', meaning: 'Kesabaran dalam menghadapi ujian.' },
  { month: 1, day: 12, horoscope: 'Capricorn', colorName: 'Slate Mountain', hex: '#34495E', meaning: 'Struktur, ambisi, dan ketahanan.' },
  { month: 1, day: 13, horoscope: 'Capricorn', colorName: 'Parrot Green', hex: '#32CD32', meaning: 'Komunikasi logis dan terstruktur.' },
  { month: 1, day: 14, horoscope: 'Capricorn', colorName: 'Deep Olive', hex: '#556B2F', meaning: 'Kebijaksanaan dari pengalaman.' },
  { month: 1, day: 15, horoscope: 'Capricorn', colorName: 'Dark Green', hex: '#013220', meaning: 'Fokus pada masa depan.' },
  { month: 1, day: 16, horoscope: 'Capricorn', colorName: 'White Lily', hex: '#F8F8FF', meaning: 'Kemurnian niat dalam bekerja.' },
  { month: 1, day: 17, horoscope: 'Capricorn', colorName: 'Sprout Green', hex: '#90EE90', meaning: 'Ide-ide praktis yang berkembang.' },
  { month: 1, day: 18, horoscope: 'Capricorn', colorName: 'Foliage', hex: '#4B5320', meaning: 'Kemampuan beradaptasi dengan realitas.' },
  { month: 1, day: 19, horoscope: 'Capricorn', colorName: 'Leaf Green', hex: '#228B22', meaning: 'Stabilitas finansial dan mental.' },
  { month: 1, day: 20, horoscope: 'Aquarius', colorName: 'Forest Green', hex: '#2E8B57', meaning: 'Koneksi dengan alam dan kemanusiaan.' },
  { month: 1, day: 21, horoscope: 'Aquarius', colorName: 'Sky Blue', hex: '#87CEEB', meaning: 'Kebebasan berpikir tanpa batas.' },
  { month: 1, day: 22, horoscope: 'Aquarius', colorName: 'Pale Cyan', hex: '#E0FFFF', meaning: 'Inovasi dan pemikiran futuristik.' },
  { month: 1, day: 23, horoscope: 'Aquarius', colorName: 'Dayflower Blue', hex: '#4682B4', meaning: 'Kejelasan visi dan eksentrisitas.' },
  { month: 1, day: 24, horoscope: 'Aquarius', colorName: 'Teal Wing', hex: '#008080', meaning: 'Keseimbangan logika dan imajinasi.' },
  { month: 1, day: 25, horoscope: 'Aquarius', colorName: 'Deep Indigo', hex: '#191970', meaning: 'Pemahaman akan misteri semesta.' },
  { month: 1, day: 26, horoscope: 'Aquarius', colorName: 'Ice Cream', hex: '#FDF5E6', meaning: 'Keterbukaan terhadap ide baru.' },
  { month: 1, day: 27, horoscope: 'Aquarius', colorName: 'Pale Lemon', hex: '#FFFACD', meaning: 'Optimisme pada perubahan sosial.' },
  { month: 1, day: 28, horoscope: 'Aquarius', colorName: 'Dandelion', hex: '#FFD700', meaning: 'Menyebarkan inspirasi ke sekeliling.' },
  { month: 1, day: 29, horoscope: 'Aquarius', colorName: 'Spring Grass', hex: '#00FF7F', meaning: 'Pembaruan dan reformasi.' },
  { month: 1, day: 30, horoscope: 'Aquarius', colorName: 'Meadow Green', hex: '#3CB371', meaning: 'Kemandirian dan harmoni.' },
  { month: 1, day: 31, horoscope: 'Aquarius', colorName: 'Bud Green', hex: '#7CFC00', meaning: 'Awal dari revolusi pemikiran.' },

  // FEBRUARI (Aquarius & Pisces) - Elemen Udara & Air (Transisi inovasi ke emosi mendalam)
  { month: 2, day: 1, horoscope: 'Aquarius', colorName: 'Cornflower Blue', hex: '#6495ED', meaning: 'Idealisme dan ketulusan niat.' },
  { month: 2, day: 2, horoscope: 'Aquarius', colorName: 'Young Purple', hex: '#9370DB', meaning: 'Intuisi yang mendukung logika.' },
  { month: 2, day: 3, horoscope: 'Aquarius', colorName: 'Electric Cyan', hex: '#00FFFF', meaning: 'Visi masa depan dan orisinalitas.' },
  { month: 2, day: 4, horoscope: 'Aquarius', colorName: 'Wisteria Purple', hex: '#C9A0DC', meaning: 'Kreativitas yang tak terduga.' },
  { month: 2, day: 5, horoscope: 'Aquarius', colorName: 'Pansy Purple', hex: '#78184A', meaning: 'Keberanian tampil beda.' },
  { month: 2, day: 6, horoscope: 'Aquarius', colorName: 'Pale Lilac', hex: '#DCD0FF', meaning: 'Empati pada masalah sosial.' },
  { month: 2, day: 7, horoscope: 'Aquarius', colorName: 'Mauvette', hex: '#E0B0FF', meaning: 'Pikiran analitis dan artistik.' },
  { month: 2, day: 8, horoscope: 'Aquarius', colorName: 'Burgundy', hex: '#800020', meaning: 'Passion tersembunyi yang kuat.' },
  { month: 2, day: 9, horoscope: 'Aquarius', colorName: 'Fuchsia Purple', hex: '#CC397B', meaning: 'Keunikan karakter yang memikat.' },
  { month: 2, day: 10, horoscope: 'Aquarius', colorName: 'Rose Red', hex: '#FF007F', meaning: 'Cinta pada kemanusiaan.' },
  { month: 2, day: 11, horoscope: 'Aquarius', colorName: 'Crimson', hex: '#DC143C', meaning: 'Semangat reformasi yang membara.' },
  { month: 2, day: 12, horoscope: 'Aquarius', colorName: 'Carmine', hex: '#960018', meaning: 'Ketegasan dalam prinsip kebebasan.' },
  { month: 2, day: 13, horoscope: 'Aquarius', colorName: 'Nightingale', hex: '#C0D860', meaning: 'Pesan kedamaian untuk semua.' },
  { month: 2, day: 14, horoscope: 'Aquarius', colorName: 'Seaweed Green', hex: '#2E8B57', meaning: 'Persahabatan yang mengakar kuat.' },
  { month: 2, day: 15, horoscope: 'Aquarius', colorName: 'Forget-me-not', hex: '#1E90FF', meaning: 'Kenangan dan memori tajam.' },
  { month: 2, day: 16, horoscope: 'Aquarius', colorName: 'Smoke Blue', hex: '#708090', meaning: 'Ketenangan di tengah kekacauan.' },
  { month: 2, day: 17, horoscope: 'Aquarius', colorName: 'Smalt', hex: '#003399', meaning: 'Fokus tinggi pada sains & teknologi.' },
  { month: 2, day: 18, horoscope: 'Aquarius', colorName: 'Chocolate', hex: '#D2691E', meaning: 'Rasa nyaman dalam komunitas.' },
  { month: 2, day: 19, horoscope: 'Pisces', colorName: 'Navy Blue', hex: '#000080', meaning: 'Kedalaman emosi lautan.' },
  { month: 2, day: 20, horoscope: 'Pisces', colorName: 'Eggshell', hex: '#F0EAD6', meaning: 'Sensitivitas dan perlindungan.' },
  { month: 2, day: 21, horoscope: 'Pisces', colorName: 'Lime Light', hex: '#E3FF00', meaning: 'Imajinasi yang bercahaya.' },
  { month: 2, day: 22, horoscope: 'Pisces', colorName: 'Turmeric', hex: '#FFC000', meaning: 'Penyembuhan energi negatif.' },
  { month: 2, day: 23, horoscope: 'Pisces', colorName: 'Mustard Flower', hex: '#FFDB58', meaning: 'Kelembutan hati dan kehangatan.' },
  { month: 2, day: 24, horoscope: 'Pisces', colorName: 'Reed Green', hex: '#7C9082', meaning: 'Fleksibilitas mengikuti arus kehidupan.' },
  { month: 2, day: 25, horoscope: 'Pisces', colorName: 'Mist White', hex: '#E6E6FA', meaning: 'Intuisi spiritual yang murni.' },
  { month: 2, day: 26, horoscope: 'Pisces', colorName: 'Leaf Reverse', hex: '#8F9779', meaning: 'Menyimpan rahasia dengan baik.' },
  { month: 2, day: 27, horoscope: 'Pisces', colorName: 'Willow Tea', hex: '#C1D8C3', meaning: 'Adaptasi empati yang luar biasa.' },
  { month: 2, day: 28, horoscope: 'Pisces', colorName: 'Olive Green', hex: '#BAB86C', meaning: 'Harapan akan kedamaian batin.' },
  { month: 2, day: 29, horoscope: 'Pisces', colorName: 'Ivy Green', hex: '#41924B', meaning: 'Keajaiban yang langka.' },

  // MARET (Pisces & Aries) - Elemen Air & Api (Mimpi yang berubah menjadi aksi)
  { month: 3, day: 1, horoscope: 'Pisces', colorName: 'Pale Salmon', hex: '#FF9999', meaning: 'Cinta kasih tanpa pamrih.' },
  { month: 3, day: 2, horoscope: 'Pisces', colorName: 'Baby Pink', hex: '#F4C2C2', meaning: 'Kepolosan dan rasa sayang.' },
  { month: 3, day: 3, horoscope: 'Pisces', colorName: 'Crested Ibis', hex: '#F5C4CB', meaning: 'Kelembutan emosi.' },
  { month: 3, day: 4, horoscope: 'Pisces', colorName: 'Poppy Red', hex: '#E25822', meaning: 'Mimpi yang penuh gairah.' },
  { month: 3, day: 5, horoscope: 'Pisces', colorName: 'Cherry Red', hex: '#D2042D', meaning: 'Daya tarik romantis yang kuat.' },
  { month: 3, day: 6, horoscope: 'Pisces', colorName: 'Cherry Blossom', hex: '#FFB7C5', meaning: 'Keindahan fana dan rasa syukur.' },
  { month: 3, day: 7, horoscope: 'Pisces', colorName: 'Salmon Pink', hex: '#FF91A4', meaning: 'Keseimbangan memberi dan menerima.' },
  { month: 3, day: 8, horoscope: 'Pisces', colorName: 'Plum Blossom', hex: '#E86F68', meaning: 'Keteguhan dalam kelembutan.' },
  { month: 3, day: 9, horoscope: 'Pisces', colorName: 'Coral', hex: '#FF7F50', meaning: 'Proteksi dari energi negatif.' },
  { month: 3, day: 10, horoscope: 'Pisces', colorName: 'Dreamy Lavender', hex: '#E6E6FA', meaning: 'Imajinasi dan empati tanpa batas.' },
  { month: 3, day: 11, horoscope: 'Pisces', colorName: 'Clay Powder', hex: '#D4B8B1', meaning: 'Kenyamanan rumah dan keluarga.' },
  { month: 3, day: 12, horoscope: 'Pisces', colorName: 'Orange Vermillion', hex: '#FF4500', meaning: 'Transisi menuju keberanian.' },
  { month: 3, day: 13, horoscope: 'Pisces', colorName: 'Persimmon', hex: '#ED4C07', meaning: 'Kegembiraan yang menular.' },
  { month: 3, day: 14, horoscope: 'Pisces', colorName: 'Scarlet', hex: '#FF2400', meaning: 'Cinta yang mengorbankan segalanya.' },
  { month: 3, day: 15, horoscope: 'Pisces', colorName: 'Rouge', hex: '#A23B6C', meaning: 'Sensualitas dan misteri.' },
  { month: 3, day: 16, horoscope: 'Pisces', colorName: 'Pale Wisteria', hex: '#E1C4FF', meaning: 'Spiritualitas dan kedamaian.' },
  { month: 3, day: 17, horoscope: 'Pisces', colorName: 'Mauve', hex: '#E0B0FF', meaning: 'Inspirasi seni yang mendalam.' },
  { month: 3, day: 18, horoscope: 'Pisces', colorName: 'Campanula Purple', hex: '#8786BF', meaning: 'Kesetiaan dan rasa syukur.' },
  { month: 3, day: 19, horoscope: 'Pisces', colorName: 'Violet', hex: '#8F00FF', meaning: 'Transformasi batin.' },
  { month: 3, day: 20, horoscope: 'Pisces', colorName: 'Ancient Purple', hex: '#895B8A', meaning: 'Kebijaksanaan spiritual tingkat tinggi.' },
  { month: 3, day: 21, horoscope: 'Aries', colorName: 'Pale Orchid', hex: '#E6A8D7', meaning: 'Keberanian yang lembut.' },
  { month: 3, day: 22, horoscope: 'Aries', colorName: 'Deep Mauve', hex: '#D473D4', meaning: 'Semangat kompetitif yang sehat.' },
  { month: 3, day: 23, horoscope: 'Aries', colorName: 'Edo Purple', hex: '#745399', meaning: 'Gengsi dan kepemimpinan.' },
  { month: 3, day: 24, horoscope: 'Aries', colorName: 'Mallow', hex: '#E290B2', meaning: 'Tindakan cepat dan tepat.' },
  { month: 3, day: 25, horoscope: 'Aries', colorName: 'Crimson Spark', hex: '#DC143C', meaning: 'Keberanian yang memicu inovasi.' },
  { month: 3, day: 26, horoscope: 'Aries', colorName: 'Silver Green', hex: '#8FBC8F', meaning: 'Vitalitas fisik yang luar biasa.' },
  { month: 3, day: 27, horoscope: 'Aries', colorName: 'Opal Green', hex: '#00FF7F', meaning: 'Fokus mengejar target.' },
  { month: 3, day: 28, horoscope: 'Aries', colorName: 'Pale Aqua', hex: '#BCD4E6', meaning: 'Pikiran jernih dalam tekanan.' },
  { month: 3, day: 29, horoscope: 'Aries', colorName: 'Spray Green', hex: '#9FE2BF', meaning: 'Dinamisme dan kecepatan.' },
  { month: 3, day: 30, horoscope: 'Aries', colorName: 'Pastel Blue', hex: '#AEC6CF', meaning: 'Kejujuran dan keterusterangan.' },
  { month: 3, day: 31, horoscope: 'Aries', colorName: 'Straw', hex: '#E4D96F', meaning: 'Aksi mandiri yang brilian.' },

  // APRIL (Aries & Taurus) - Elemen Api & Tanah (Dari inisiatif ke konsistensi)
  { month: 4, day: 1, horoscope: 'Aries', colorName: 'Pale Cherry', hex: '#FFB7C5', meaning: 'Semangat yang menyegarkan.' },
  { month: 4, day: 2, horoscope: 'Aries', colorName: 'Shell Pink', hex: '#FFB6C1', meaning: 'Optimisme pantang menyerah.' },
  { month: 4, day: 3, horoscope: 'Aries', colorName: 'Fuchsia Pink', hex: '#FF77FF', meaning: 'Energi meledak-ledak.' },
  { month: 4, day: 4, horoscope: 'Aries', colorName: 'Deep Orchid Pink', hex: '#E29CD2', meaning: 'Daya juang dan keberanian.' },
  { month: 4, day: 5, horoscope: 'Aries', colorName: 'Blue Wisteria', hex: '#84A2D4', meaning: 'Ketangkasan logika.' },
  { month: 4, day: 6, horoscope: 'Aries', colorName: 'Chalk Blue', hex: '#5688B0', meaning: 'Inisiatif kepemimpinan.' },
  { month: 4, day: 7, horoscope: 'Aries', colorName: 'White Lily', hex: '#F8F8FF', meaning: 'Kepercayaan diri tinggi.' },
  { month: 4, day: 8, horoscope: 'Aries', colorName: 'Pale Green', hex: '#98FB98', meaning: 'Awal yang dinamis.' },
  { month: 4, day: 9, horoscope: 'Aries', colorName: 'Gardenia', hex: '#F7E7CE', meaning: 'Pikiran yang tajam.' },
  { month: 4, day: 10, horoscope: 'Aries', colorName: 'Pumpkin', hex: '#FF7518', meaning: 'Antusiasme berapi-api.' },
  { month: 4, day: 11, horoscope: 'Aries', colorName: 'Steamed Chestnut', hex: '#DBC381', meaning: 'Kemauan keras.' },
  { month: 4, day: 12, horoscope: 'Aries', colorName: 'Tea White', hex: '#E5D6A7', meaning: 'Kesederhanaan dalam bertindak.' },
  { month: 4, day: 13, horoscope: 'Aries', colorName: 'Frosty Gray', hex: '#E6E8FA', meaning: 'Pikiran strategis.' },
  { month: 4, day: 14, horoscope: 'Aries', colorName: 'Mouse Gray', hex: '#787C85', meaning: 'Keberanian menghadapi risiko.' },
  { month: 4, day: 15, horoscope: 'Aries', colorName: 'Pale Mist White', hex: '#E8EDF2', meaning: 'Fokus pada hasil cepat.' },
  { month: 4, day: 16, horoscope: 'Aries', colorName: 'Sky Gray', hex: '#B8C3D3', meaning: 'Ambisi merengkuh puncak.' },
  { month: 4, day: 17, horoscope: 'Aries', colorName: 'Battleship Gray', hex: '#848482', meaning: 'Mental pejuang.' },
  { month: 4, day: 18, horoscope: 'Aries', colorName: 'Slate Gray', hex: '#708090', meaning: 'Kekuatan fisik.' },
  { month: 4, day: 19, horoscope: 'Aries', colorName: 'Charcoal', hex: '#36454F', meaning: 'Determinasi tak tergoyahkan.' },
  { month: 4, day: 20, horoscope: 'Taurus', colorName: 'Young Seedling', hex: '#90EE90', meaning: 'Kesabaran menumbuhkan hasil.' },
  { month: 4, day: 21, horoscope: 'Taurus', colorName: 'Fresh Greens', hex: '#00FF00', meaning: 'Harmoni dengan material.' },
  { month: 4, day: 22, horoscope: 'Taurus', colorName: 'Parrot Green', hex: '#32CD32', meaning: 'Menikmati keindahan alam.' },
  { month: 4, day: 23, horoscope: 'Taurus', colorName: 'Reed Leaf', hex: '#8F9779', meaning: 'Ketenangan batin.' },
  { month: 4, day: 24, horoscope: 'Taurus', colorName: 'Sprout', hex: '#A2E4B8', meaning: 'Stabilitas finansial.' },
  { month: 4, day: 25, horoscope: 'Taurus', colorName: 'Herb', hex: '#4B5320', meaning: 'Kenyamanan indrawi.' },
  { month: 4, day: 26, horoscope: 'Taurus', colorName: 'Deep Pea Green', hex: '#2E8B57', meaning: 'Kesetiaan pada pasangan.' },
  { month: 4, day: 27, horoscope: 'Taurus', colorName: 'Emerald Green', hex: '#50C878', meaning: 'Kelimpahan dan kemewahan.' },
  { month: 4, day: 28, horoscope: 'Taurus', colorName: 'Turquoise Green', hex: '#A0D6B4', meaning: 'Seni dan estetika.' },
  { month: 4, day: 29, horoscope: 'Taurus', colorName: 'Pale Cyan', hex: '#87D3F8', meaning: 'Kepercayaan yang dapat diandalkan.' },
  { month: 4, day: 30, horoscope: 'Taurus', colorName: 'Azure Blue', hex: '#007FFF', meaning: 'Dedikasi pada pekerjaan.' },

  // MEI (Taurus & Gemini) - Elemen Tanah & Udara (Kestabilan bergeser ke rasa ingin tahu)
  { month: 5, day: 1, horoscope: 'Taurus', colorName: 'Turquoise', hex: '#40E0D0', meaning: 'Penghargaan pada kualitas.' },
  { month: 5, day: 2, horoscope: 'Taurus', colorName: 'Earthy Emerald', hex: '#2ECC71', meaning: 'Kestabilan dan pertumbuhan natural.' },
  { month: 5, day: 3, horoscope: 'Taurus', colorName: 'Teal Green', hex: '#008080', meaning: 'Pemikiran praktis.' },
  { month: 5, day: 4, horoscope: 'Taurus', colorName: 'Teal Blue', hex: '#367588', meaning: 'Keteguhan memegang janji.' },
  { month: 5, day: 5, horoscope: 'Taurus', colorName: 'Light Blue', hex: '#ADD8E6', meaning: 'Ketenangan dalam rutinitas.' },
  { month: 5, day: 6, horoscope: 'Taurus', colorName: 'Forget-me-not Blue', hex: '#66B2FF', meaning: 'Memori yang sangat baik.' },
  { month: 5, day: 7, horoscope: 'Taurus', colorName: 'Ultramarine', hex: '#120A8F', meaning: 'Kedalaman nilai tradisional.' },
  { month: 5, day: 8, horoscope: 'Taurus', colorName: 'Thousand Year Green', hex: '#315535', meaning: 'Ketahanan menghadapi krisis.' },
  { month: 5, day: 9, horoscope: 'Taurus', colorName: 'Parakeet Green', hex: '#55C6A9', meaning: 'Rasa aman dalam rumah.' },
  { month: 5, day: 10, horoscope: 'Taurus', colorName: 'Eggshell', hex: '#F0EAD6', meaning: 'Perhatian pada detail seni.' },
  { month: 5, day: 11, horoscope: 'Taurus', colorName: 'Lettuce Green', hex: '#BEE687', meaning: 'Nutrisi untuk jiwa.' },
  { month: 5, day: 12, horoscope: 'Taurus', colorName: 'Chartreuse Yellow', hex: '#DFFF00', meaning: 'Sikap optimis pragmatis.' },
  { month: 5, day: 13, horoscope: 'Taurus', colorName: 'Dry Grass', hex: '#E4D5B7', meaning: 'Konsistensi dan ritme kerja.' },
  { month: 5, day: 14, horoscope: 'Taurus', colorName: 'Olive', hex: '#808000', meaning: 'Kekuatan pelindung.' },
  { month: 5, day: 15, horoscope: 'Taurus', colorName: 'Colonial Yellow', hex: '#F3E5AB', meaning: 'Kenyamanan elegan.' },
  { month: 5, day: 16, horoscope: 'Taurus', colorName: 'Pale Mustard', hex: '#EEDC82', meaning: 'Kesabaran membuahkan hasil emas.' },
  { month: 5, day: 17, horoscope: 'Taurus', colorName: 'Golden Ocher', hex: '#DFB15B', meaning: 'Investasi dan kekayaan.' },
  { month: 5, day: 18, horoscope: 'Taurus', colorName: 'Olive Brown', hex: '#6B8E23', meaning: 'Kehandalan dalam tim.' },
  { month: 5, day: 19, horoscope: 'Taurus', colorName: 'Thousand Year Brown', hex: '#4B3E2A', meaning: 'Kebijaksanaan kuno.' },
  { month: 5, day: 20, horoscope: 'Taurus', colorName: 'Deep Aqua', hex: '#008B8B', meaning: 'Ketulusan kasih sayang.' },
  { month: 5, day: 21, horoscope: 'Gemini', colorName: 'Verdigris', hex: '#43B3AE', meaning: 'Komunikasi yang memikat.' },
  { month: 5, day: 22, horoscope: 'Gemini', colorName: 'Spruce Green', hex: '#004225', meaning: 'Fleksibilitas pemikiran.' },
  { month: 5, day: 23, horoscope: 'Gemini', colorName: 'Bottle Green', hex: '#006A4E', meaning: 'Banyak minat dan bakat.' },
  { month: 5, day: 24, horoscope: 'Gemini', colorName: 'Cypress Green', hex: '#005826', meaning: 'Kecepatan menangkap informasi.' },
  { month: 5, day: 25, horoscope: 'Gemini', colorName: 'Naples Yellow', hex: '#FADA5E', meaning: 'Keceriaan intelektual.' },
  { month: 5, day: 26, horoscope: 'Gemini', colorName: 'Marigold Yellow', hex: '#F3A505', meaning: 'Sosialisasi yang hangat.' },
  { month: 5, day: 27, horoscope: 'Gemini', colorName: 'Golden Yellow', hex: '#FFC000', meaning: 'Ide brilian yang konstan.' },
  { month: 5, day: 28, horoscope: 'Gemini', colorName: 'Old Gold', hex: '#CFB53B', meaning: 'Kepandaian bernegosiasi.' },
  { month: 5, day: 29, horoscope: 'Gemini', colorName: 'Coffee Brown', hex: '#4A2C2A', meaning: 'Energi sosial tinggi.' },
  { month: 5, day: 30, horoscope: 'Gemini', colorName: 'Ash Sakura', hex: '#E8D3D1', meaning: 'Rasa ingin tahu yang manis.' },
  { month: 5, day: 31, horoscope: 'Gemini', colorName: 'Pale Crimson', hex: '#F8B8C6', meaning: 'Humor dan kecerdasan.' },

  // JUNI (Gemini & Cancer) - Elemen Udara & Air (Intelektual beralih ke rasa protektif)
  { month: 6, day: 1, horoscope: 'Gemini', colorName: 'Pale Crocus', hex: '#CBA0D1', meaning: 'Adaptasi yang luwes.' },
  { month: 6, day: 2, horoscope: 'Gemini', colorName: 'Violet', hex: '#8F00FF', meaning: 'Kefasihan berbicara.' },
  { month: 6, day: 3, horoscope: 'Gemini', colorName: 'Plum', hex: '#DDA0DD', meaning: 'Dinamisme sosial.' },
  { month: 6, day: 4, horoscope: 'Gemini', colorName: 'Pale White Lily', hex: '#F6F6F6', meaning: 'Pemikiran tanpa bias.' },
  { month: 6, day: 5, horoscope: 'Gemini', colorName: 'Pale Fresh Green', hex: '#C2F2C2', meaning: 'Gagasan segar.' },
  { month: 6, day: 6, horoscope: 'Gemini', colorName: 'Melon Yellow', hex: '#F8DE7E', meaning: 'Daya tarik ekstrovert.' },
  { month: 6, day: 7, horoscope: 'Gemini', colorName: 'Elm Green', hex: '#1C542D', meaning: 'Kecerdasan menganalisa.' },
  { month: 6, day: 8, horoscope: 'Gemini', colorName: 'Olive Drab', hex: '#6B8E23', meaning: 'Objektivitas.' },
  { month: 6, day: 9, horoscope: 'Gemini', colorName: 'Cream', hex: '#FFFDD0', meaning: 'Menyatukan dua perspektif.' },
  { month: 6, day: 10, horoscope: 'Gemini', colorName: 'Lemon Yellow', hex: '#FFF44F', meaning: 'Logika yang terang.' },
  { month: 6, day: 11, horoscope: 'Gemini', colorName: 'Daffodil', hex: '#FFFF31', meaning: 'Spontanitas.' },
  { month: 6, day: 12, horoscope: 'Gemini', colorName: 'Saffron Yellow', hex: '#F4C430', meaning: 'Pengetahuan yang luas.' },
  { month: 6, day: 13, horoscope: 'Gemini', colorName: 'Sunflower', hex: '#FFC512', meaning: 'Karizma di depan publik.' },
  { month: 6, day: 14, horoscope: 'Gemini', colorName: 'Ivory', hex: '#FFFFF0', meaning: 'Keterampilan menulis.' },
  { month: 6, day: 15, horoscope: 'Gemini', colorName: 'Breezy Yellow', hex: '#F1C40F', meaning: 'Pikiran cerah dan komunikasi dinamis.' },
  { month: 6, day: 16, horoscope: 'Gemini', colorName: 'Ochre', hex: '#CC7722', meaning: 'Kefasihan berbagai bahasa.' },
  { month: 6, day: 17, horoscope: 'Gemini', colorName: 'Old Rose', hex: '#C08081', meaning: 'Romansa intelektual.' },
  { month: 6, day: 18, horoscope: 'Gemini', colorName: 'Mahogany Brown', hex: '#420C09', meaning: 'Kecerdikan berbisnis.' },
  { month: 6, day: 19, horoscope: 'Gemini', colorName: 'Egg Yolk', hex: '#FAD61D', meaning: 'Kekayaan ide.' },
  { month: 6, day: 20, horoscope: 'Gemini', colorName: 'Sunlight Yellow', hex: '#FFEF00', meaning: 'Pikiran yang selalu aktif.' },
  { month: 6, day: 21, horoscope: 'Cancer', colorName: 'Golden Brown', hex: '#996515', meaning: 'Perasaan keibuan/kebapakan.' },
  { month: 6, day: 22, horoscope: 'Cancer', colorName: 'Garnet Brown', hex: '#911616', meaning: 'Ikatan keluarga.' },
  { month: 6, day: 23, horoscope: 'Cancer', colorName: 'Maroon', hex: '#800000', meaning: 'Proteksi pada yang lemah.' },
  { month: 6, day: 24, horoscope: 'Cancer', colorName: 'Light Orchid Pink', hex: '#E6A8D7', meaning: 'Kelembutan emosional.' },
  { month: 6, day: 25, horoscope: 'Cancer', colorName: 'Pale Cherry Pink', hex: '#FFC0CB', meaning: 'Empati yang dalam.' },
  { month: 6, day: 26, horoscope: 'Cancer', colorName: 'Carnation Pink', hex: '#FFA6C9', meaning: 'Ketulusan kasih.' },
  { month: 6, day: 27, horoscope: 'Cancer', colorName: 'Rose Pink', hex: '#FF66CC', meaning: 'Cinta pada memori masa lalu.' },
  { month: 6, day: 28, horoscope: 'Cancer', colorName: 'Pepper Red', hex: '#8B0000', meaning: 'Ketegasan melindungi keluarga.' },
  { month: 6, day: 29, horoscope: 'Cancer', colorName: 'Baby Blue', hex: '#89CFF0', meaning: 'Insting merawat.' },
  { month: 6, day: 30, horoscope: 'Cancer', colorName: 'Pale Ultramarine', hex: '#8A9A5B', meaning: 'Kepekaan batin.' },

  // JULI (Cancer & Leo) - Elemen Air & Api (Intuisi beralih ke ekspresi diri)
  { month: 7, day: 1, horoscope: 'Cancer', colorName: 'Duck Blue', hex: '#007791', meaning: 'Keteguhan hati yang tenang.' },
  { month: 7, day: 2, horoscope: 'Cancer', colorName: 'Cobalt Blue', hex: '#0047AB', meaning: 'Penyembuh luka batin.' },
  { month: 7, day: 3, horoscope: 'Cancer', colorName: 'Ink Blue', hex: '#003153', meaning: 'Kekayaan perasaan tersembunyi.' },
  { month: 7, day: 4, horoscope: 'Cancer', colorName: 'Aqua', hex: '#00FFFF', meaning: 'Kedamaian di rumah.' },
  { month: 7, day: 5, horoscope: 'Cancer', colorName: 'Pale Sax Blue', hex: '#4682B4', meaning: 'Kesetiaan pada pasangan.' },
  { month: 7, day: 6, horoscope: 'Cancer', colorName: 'Shinbashi Blue', hex: '#59B9C6', meaning: 'Sensitivitas artistik.' },
  { month: 7, day: 7, horoscope: 'Cancer', colorName: 'Blue Canal', hex: '#006D8A', meaning: 'Intuisi yang menuntun.' },
  { month: 7, day: 8, horoscope: 'Cancer', colorName: 'Marine Blue', hex: '#1E3F66', meaning: 'Rasa aman mendalam.' },
  { month: 7, day: 9, horoscope: 'Cancer', colorName: 'Pearl White', hex: '#EAEEE9', meaning: 'Kemurnian cinta.' },
  { month: 7, day: 10, horoscope: 'Cancer', colorName: 'Oceanic Teal', hex: '#1ABC9C', meaning: 'Kedalaman emosi dan intuisi yang jernih.' },
  { month: 7, day: 11, horoscope: 'Cancer', colorName: 'Lavender Blue', hex: '#CCCCFF', meaning: 'Pengorbanan tulus.' },
  { month: 7, day: 12, horoscope: 'Cancer', colorName: 'Majolica Blue', hex: '#182C61', meaning: 'Kekuatan memori emosional.' },
  { month: 7, day: 13, horoscope: 'Cancer', colorName: 'Prussian Blue', hex: '#003153', meaning: 'Pemahaman karakter orang lain.' },
  { month: 7, day: 14, horoscope: 'Cancer', colorName: 'Deep Baby Pink', hex: '#E75480', meaning: 'Kasih sayang tak terbatas.' },
  { month: 7, day: 15, horoscope: 'Cancer', colorName: 'Pale Mauvette', hex: '#E0B0FF', meaning: 'Nostalgia dan tradisi.' },
  { month: 7, day: 16, horoscope: 'Cancer', colorName: 'Fountain Blue', hex: '#5CACEE', meaning: 'Memberi nutrisi batin.' },
  { month: 7, day: 17, horoscope: 'Cancer', colorName: 'Salvia Blue', hex: '#4B3621', meaning: 'Perhatian pada detail domestik.' },
  { month: 7, day: 18, horoscope: 'Cancer', colorName: 'Royal Purple', hex: '#7851A9', meaning: 'Kebanggaan pada asal usul.' },
  { month: 7, day: 19, horoscope: 'Cancer', colorName: 'Deep Shell Pink', hex: '#E9967A', meaning: 'Kehangatan pelukan.' },
  { month: 7, day: 20, horoscope: 'Cancer', colorName: 'Wheat', hex: '#F5DEB3', meaning: 'Penyedia kebutuhan.' },
  { month: 7, day: 21, horoscope: 'Cancer', colorName: 'Havana Rose', hex: '#D77A7C', meaning: 'Kenyamanan emosi.' },
  { month: 7, day: 22, horoscope: 'Cancer', colorName: 'Carmine Red', hex: '#960018', meaning: 'Kesetiaan absolut.' },
  { month: 7, day: 23, horoscope: 'Leo', colorName: 'Madder Red', hex: '#A81C07', meaning: 'Keberanian tampil beda.' },
  { month: 7, day: 24, horoscope: 'Leo', colorName: 'Cupid Pink', hex: '#FFB6C1', meaning: 'Daya tarik romantis yang kuat.' },
  { month: 7, day: 25, horoscope: 'Leo', colorName: 'Lotus Pink', hex: '#FFB6C1', meaning: 'Karisma alami.' },
  { month: 7, day: 26, horoscope: 'Leo', colorName: 'Rose Madder', hex: '#E32636', meaning: 'Jiwa kepemimpinan.' },
  { month: 7, day: 27, horoscope: 'Leo', colorName: 'Crimson', hex: '#DC143C', meaning: 'Gairah hidup yang menyala.' },
  { month: 7, day: 28, horoscope: 'Leo', colorName: 'Black Persimmon', hex: '#2B2B2B', meaning: 'Otoritas dan kehormatan.' },
  { month: 7, day: 29, horoscope: 'Leo', colorName: 'Cerulean Blue', hex: '#007BA7', meaning: 'Visi yang besar.' },
  { month: 7, day: 30, horoscope: 'Leo', colorName: 'Peacock Blue', hex: '#33A1C9', meaning: 'Kebanggaan diri.' },
  { month: 7, day: 31, horoscope: 'Leo', colorName: 'Prussian Blue', hex: '#003153', meaning: 'Pengaruh dominan.' },

  // AGUSTUS (Leo & Virgo) - Elemen Api & Tanah (Dari sorotan ke detail pekerjaan)
  { month: 8, day: 1, horoscope: 'Leo', colorName: 'Blue Shell', hex: '#9BB8D7', meaning: 'Pesona eksklusif.' },
  { month: 8, day: 2, horoscope: 'Leo', colorName: 'Pale Yacht Blue', hex: '#87CEEB', meaning: 'Kedermawanan hati.' },
  { month: 8, day: 3, horoscope: 'Leo', colorName: 'Yacht Blue', hex: '#00BFFF', meaning: 'Ambisi sukses besar.' },
  { month: 8, day: 4, horoscope: 'Leo', colorName: 'Cyan Blue', hex: '#00FFFF', meaning: 'Kreativitas tanpa rasa takut.' },
  { month: 8, day: 5, horoscope: 'Leo', colorName: 'Lapis Lazuli', hex: '#26619C', meaning: 'Kemuliaan karakter.' },
  { month: 8, day: 6, horoscope: 'Leo', colorName: 'Lapis Lazuli', hex: '#26619C', meaning: 'Kepercayaan diri tinggi.' },
  { month: 8, day: 7, horoscope: 'Leo', colorName: 'Royal Blue', hex: '#4169E1', meaning: 'Sikap ningrat.' },
  { month: 8, day: 8, horoscope: 'Leo', colorName: 'Majestic Gold', hex: '#F39C12', meaning: 'Kepemimpinan dan kehangatan yang bersinar.' },
  { month: 8, day: 9, horoscope: 'Leo', colorName: 'Navy Blue', hex: '#000080', meaning: 'Pengorganisasian massa.' },
  { month: 8, day: 10, horoscope: 'Leo', colorName: 'Hydrangea Blue', hex: '#8FAADC', meaning: 'Daya pikat estetis.' },
  { month: 8, day: 11, horoscope: 'Leo', colorName: 'Mulberry', hex: '#C54B8C', meaning: 'Dramatisasi positif.' },
  { month: 8, day: 12, horoscope: 'Leo', colorName: 'Wisteria Mouse', hex: '#766980', meaning: 'Kemewahan elegan.' },
  { month: 8, day: 13, horoscope: 'Leo', colorName: 'White Blue', hex: '#AEEEEE', meaning: 'Perhatian penuh dari orang lain.' },
  { month: 8, day: 14, horoscope: 'Leo', colorName: 'Myosotis', hex: '#5CACEE', meaning: 'Popularitas abadi.' },
  { month: 8, day: 15, horoscope: 'Leo', colorName: 'Yellow', hex: '#FFFF00', meaning: 'Pusat energi dan kebahagiaan.' },
  { month: 8, day: 16, horoscope: 'Leo', colorName: 'Light Cream', hex: '#FFFDD0', meaning: 'Kebaikan hati yang polos.' },
  { month: 8, day: 17, horoscope: 'Leo', colorName: 'Primrose Yellow', hex: '#F6E14F', meaning: 'Optimisme yang menular.' },
  { month: 8, day: 18, horoscope: 'Leo', colorName: 'Citrus', hex: '#FFA500', meaning: 'Kegembiraan yang meluap.' },
  { month: 8, day: 19, horoscope: 'Leo', colorName: 'Golden Orange', hex: '#FFAE42', meaning: 'Kesuksesan material.' },
  { month: 8, day: 20, horoscope: 'Leo', colorName: 'Mandarin Orange', hex: '#FF8C00', meaning: 'Vitalitas tak habis-habis.' },
  { month: 8, day: 21, horoscope: 'Leo', colorName: 'Cinnamon', hex: '#D2691E', meaning: 'Kehangatan yang memotivasi.' },
  { month: 8, day: 22, horoscope: 'Leo', colorName: 'Golden Corn', hex: '#F0E68C', meaning: 'Hasil panen kejayaan.' },
  { month: 8, day: 23, horoscope: 'Virgo', colorName: 'Deep Sunflower', hex: '#FFC512', meaning: 'Fokus pada kesempurnaan.' },
  { month: 8, day: 24, horoscope: 'Virgo', colorName: 'Yellow Ocher', hex: '#CB9D06', meaning: 'Kecerdasan analitis.' },
  { month: 8, day: 25, horoscope: 'Virgo', colorName: 'Buff', hex: '#F0DC82', meaning: 'Kerajinan dan ketelitian.' },
  { month: 8, day: 26, horoscope: 'Virgo', colorName: 'Tobacco Brown', hex: '#715E4C', meaning: 'Dedikasi melayani.' },
  { month: 8, day: 27, horoscope: 'Virgo', colorName: 'Sky Blue', hex: '#87CEEB', meaning: 'Kerapian dan keteraturan.' },
  { month: 8, day: 28, horoscope: 'Virgo', colorName: 'Aqua Gray', hex: '#80B3C4', meaning: 'Praktikalitas.' },
  { month: 8, day: 29, horoscope: 'Virgo', colorName: 'Pale Salvia Blue', hex: '#9CB2D5', meaning: 'Kemampuan healing.' },
  { month: 8, day: 30, horoscope: 'Virgo', colorName: 'Ultramarine', hex: '#120A8F', meaning: 'Metodologi kerja yang presisi.' },
  { month: 8, day: 31, horoscope: 'Virgo', colorName: 'Purple Navy', hex: '#4E5180', meaning: 'Kritis namun konstruktif.' },

  // SEPTEMBER (Virgo & Libra) - Elemen Tanah & Udara (Ketelitian berpadu harmoni estetika)
  { month: 9, day: 1, horoscope: 'Virgo', colorName: 'Fresh Green', hex: '#69B34C', meaning: 'Kesehatan dan higienitas.' },
  { month: 9, day: 2, horoscope: 'Virgo', colorName: 'Pasture Green', hex: '#7CFC00', meaning: 'Kerja keras di alam nyata.' },
  { month: 9, day: 3, horoscope: 'Virgo', colorName: 'Holly Green', hex: '#005826', meaning: 'Disiplin moral.' },
  { month: 9, day: 4, horoscope: 'Virgo', colorName: 'Viridian', hex: '#40826D', meaning: 'Pemecahan masalah sistematis.' },
  { month: 9, day: 5, horoscope: 'Virgo', colorName: 'Iron Blue', hex: '#1C352D', meaning: 'Kuat memegang prinsip.' },
  { month: 9, day: 6, horoscope: 'Virgo', colorName: 'Sea Pine Blue', hex: '#244F59', meaning: 'Ketahanan pikiran.' },
  { month: 9, day: 7, horoscope: 'Virgo', colorName: 'Pale Water', hex: '#D4F0F0', meaning: 'Intelektual jernih.' },
  { month: 9, day: 8, horoscope: 'Virgo', colorName: 'Aquamarine', hex: '#7FFFD4', meaning: 'Perhatian pada kebersihan.' },
  { month: 9, day: 9, horoscope: 'Virgo', colorName: 'Deep Teal Green', hex: '#004B49', meaning: 'Efisien dan rasional.' },
  { month: 9, day: 10, horoscope: 'Virgo', colorName: 'Iron Navy', hex: '#252850', meaning: 'Kesopanan dan tata krama.' },
  { month: 9, day: 11, horoscope: 'Virgo', colorName: 'Blue Plus', hex: '#314E6B', meaning: 'Kemampuan mengorganisasi detail.' },
  { month: 9, day: 12, horoscope: 'Virgo', colorName: 'Earthy Clay', hex: '#D35400', meaning: 'Ketelitian dan dedikasi pada detail.' },
  { month: 9, day: 13, horoscope: 'Virgo', colorName: 'Purple Navy', hex: '#4E5180', meaning: 'Evaluasi diri yang kuat.' },
  { month: 9, day: 14, horoscope: 'Virgo', colorName: 'Tan', hex: '#D2B48C', meaning: 'Kesetiaan pada tanggung jawab.' },
  { month: 9, day: 15, horoscope: 'Virgo', colorName: 'Brown', hex: '#964B00', meaning: 'Kesederhanaan yang fungsional.' },
  { month: 9, day: 16, horoscope: 'Virgo', colorName: 'Terracotta', hex: '#E2725B', meaning: 'Produktivitas tinggi.' },
  { month: 9, day: 17, horoscope: 'Virgo', colorName: 'Light Blue Mouse', hex: '#87CEFA', meaning: 'Keikhlasan membantu.' },
  { month: 9, day: 18, horoscope: 'Virgo', colorName: 'Powder Blue', hex: '#B0E0E6', meaning: 'Ketajaman pikiran logis.' },
  { month: 9, day: 19, horoscope: 'Virgo', colorName: 'Lilac Haze', hex: '#C8A2C8', meaning: 'Keseriusan belajar.' },
  { month: 9, day: 20, horoscope: 'Virgo', colorName: 'Light Lemon', hex: '#FFFACD', meaning: 'Pikiran kritis yang sehat.' },
  { month: 9, day: 21, horoscope: 'Virgo', colorName: 'Tea Green', hex: '#D0F0C0', meaning: 'Ketenangan analisis.' },
  { month: 9, day: 22, horoscope: 'Virgo', colorName: 'Bourgeon', hex: '#8B4513', meaning: 'Kehandalan sistem.' },
  { month: 9, day: 23, horoscope: 'Libra', colorName: 'Joan Lemonade', hex: '#FFFACD', meaning: 'Toleransi dan negosiasi.' },
  { month: 9, day: 24, horoscope: 'Libra', colorName: 'Green Finch', hex: '#C3D825', meaning: 'Sikap adil dan proporsional.' },
  { month: 9, day: 25, horoscope: 'Libra', colorName: 'Sun Orange', hex: '#FF8C00', meaning: 'Karisma sosial dan keindahan.' },
  { month: 9, day: 26, horoscope: 'Libra', colorName: 'Tangerine Orange', hex: '#FFA089', meaning: 'Pencinta estetika.' },
  { month: 9, day: 27, horoscope: 'Libra', colorName: 'Tiger Lily', hex: '#FF6347', meaning: 'Diplomasi yang hangat.' },
  { month: 9, day: 28, horoscope: 'Libra', colorName: 'Scarlet', hex: '#FF2400', meaning: 'Keberanian mencari keadilan.' },
  { month: 9, day: 29, horoscope: 'Libra', colorName: 'Opera', hex: '#FF008C', meaning: 'Kesenian dan selera tinggi.' },
  { month: 9, day: 30, horoscope: 'Libra', colorName: 'Amaranth Purple', hex: '#AB274F', meaning: 'Kemitraan yang harmonis.' },

  // OKTOBER (Libra & Scorpio) - Elemen Udara & Air (Keseimbangan menuju misteri terdalam)
  { month: 10, day: 1, horoscope: 'Libra', colorName: 'Yellow Cinnabar', hex: '#E36C09', meaning: 'Kebersamaan dan romansa.' },
  { month: 10, day: 2, horoscope: 'Libra', colorName: 'Bengal Red', hex: '#A84E34', meaning: 'Sikap elegan.' },
  { month: 10, day: 3, horoscope: 'Libra', colorName: 'Carrot Orange', hex: '#ED9121', meaning: 'Kehangatan keramahan.' },
  { month: 10, day: 4, horoscope: 'Libra', colorName: 'Flame Orange', hex: '#FF4500', meaning: 'Daya tarik menawan.' },
  { month: 10, day: 5, horoscope: 'Libra', colorName: 'Harmonic Pink', hex: '#FFB6C1', meaning: 'Keseimbangan dan keindahan estetika.' },
  { month: 10, day: 6, horoscope: 'Libra', colorName: 'Cinnamon', hex: '#D2691E', meaning: 'Kehalusan tutur kata.' },
  { month: 10, day: 7, horoscope: 'Libra', colorName: 'Cafe Au Lait', hex: '#A67B5B', meaning: 'Kenyamanan mengobrol.' },
  { month: 10, day: 8, horoscope: 'Libra', colorName: 'Brick Red', hex: '#CB4154', meaning: 'Stabilitas hubungan persahabatan.' },
  { month: 10, day: 9, horoscope: 'Libra', colorName: 'Terra Rosa', hex: '#C67468', meaning: 'Pesona artistik.' },
  { month: 10, day: 10, horoscope: 'Libra', colorName: 'Ochre', hex: '#CC7722', meaning: 'Selera busana yang baik.' },
  { month: 10, day: 11, horoscope: 'Libra', colorName: 'Camel', hex: '#C19A6B', meaning: 'Objektivitas menilai situasi.' },
  { month: 10, day: 12, horoscope: 'Libra', colorName: 'Burnt Sienna', hex: '#E97451', meaning: 'Keanggunan klasik.' },
  { month: 10, day: 13, horoscope: 'Libra', colorName: 'Chestnut Brown', hex: '#5D4037', meaning: 'Kemampuan mediasi.' },
  { month: 10, day: 14, horoscope: 'Libra', colorName: 'Sepia', hex: '#704214', meaning: 'Apresiasi pada sejarah seni.' },
  { month: 10, day: 15, horoscope: 'Libra', colorName: 'Red Ocher', hex: '#A95C68', meaning: 'Kebijaksanaan bergaul.' },
  { month: 10, day: 16, horoscope: 'Libra', colorName: 'Topaz', hex: '#FFC87C', meaning: 'Gaya yang mewah.' },
  { month: 10, day: 17, horoscope: 'Libra', colorName: 'Orchid White', hex: '#FDF5E6', meaning: 'Pikiran netral.' },
  { month: 10, day: 18, horoscope: 'Libra', colorName: 'Pearl Gray', hex: '#C0C0C0', meaning: 'Harmoni ruang dan warna.' },
  { month: 10, day: 19, horoscope: 'Libra', colorName: 'Silver Mouse', hex: '#C0C0C0', meaning: 'Kedamaian tanpa konflik.' },
  { month: 10, day: 20, horoscope: 'Libra', colorName: 'Mouse Gray', hex: '#787C85', meaning: 'Keadilan hukum.' },
  { month: 10, day: 21, horoscope: 'Libra', colorName: 'Pigeon Purple', hex: '#877085', meaning: 'Cinta kedamaian abadi.' },
  { month: 10, day: 22, horoscope: 'Libra', colorName: 'Lithograph', hex: '#708090', meaning: 'Kepekaan visual tinggi.' },
  { month: 10, day: 23, horoscope: 'Scorpio', colorName: 'Mustard', hex: '#FFDB58', meaning: 'Ketajaman insting.' },
  { month: 10, day: 24, horoscope: 'Scorpio', colorName: 'Sea Moss', hex: '#738276', meaning: 'Kekuatan regenerasi.' },
  { month: 10, day: 25, horoscope: 'Scorpio', colorName: 'Rose Gray', hex: '#A899A6', meaning: 'Rahasia yang terjaga.' },
  { month: 10, day: 26, horoscope: 'Scorpio', colorName: 'Light Turquoise', hex: '#AFE4DE', meaning: 'Kekuatan magis terselubung.' },
  { month: 10, day: 27, horoscope: 'Scorpio', colorName: 'Rusty Door', hex: '#593B32', meaning: 'Investigasi dan kebenaran.' },
  { month: 10, day: 28, horoscope: 'Scorpio', colorName: 'Pigeon Purple', hex: '#877085', meaning: 'Sensualitas magnetis.' },
  { month: 10, day: 29, horoscope: 'Scorpio', colorName: 'Chestnut', hex: '#954535', meaning: 'Fokus intens pada tujuan.' },
  { month: 10, day: 30, horoscope: 'Scorpio', colorName: 'Vineyard', hex: '#722F37', meaning: 'Transformasi batin.' },
  { month: 10, day: 31, horoscope: 'Scorpio', colorName: 'Lilac', hex: '#C8A2C8', meaning: 'Kekuatan penyembuhan mendalam.' },

  // NOVEMBER (Scorpio & Sagittarius) - Elemen Air & Api (Misteri meledak menjadi kebebasan eksplorasi)
  { month: 11, day: 1, horoscope: 'Scorpio', colorName: 'Camel', hex: '#C19A6B', meaning: 'Kemauan menembus batas.' },
  { month: 11, day: 2, horoscope: 'Scorpio', colorName: 'Fawn', hex: '#E5A073', meaning: 'Intuisi membaca niat orang.' },
  { month: 11, day: 3, horoscope: 'Scorpio', colorName: 'Dark Brown', hex: '#654321', meaning: 'Ketahanan emosional.' },
  { month: 11, day: 4, horoscope: 'Scorpio', colorName: 'Taupe', hex: '#483C32', meaning: 'Analisis psikologis.' },
  { month: 11, day: 5, horoscope: 'Scorpio', colorName: 'Charcoal Gray', hex: '#36454F', meaning: 'Penentuan sikap ekstrem.' },
  { month: 11, day: 6, horoscope: 'Scorpio', colorName: 'Joan Donor Pull', hex: '#F3E5AB', meaning: 'Daya tarik fatal.' },
  { month: 11, day: 7, horoscope: 'Scorpio', colorName: 'Sunflower', hex: '#FFC512', meaning: 'Kemenangan dari krisis.' },
  { month: 11, day: 8, horoscope: 'Scorpio', colorName: 'Nasturtium Orange', hex: '#FF7F00', meaning: 'Gairah yang intens.' },
  { month: 11, day: 9, horoscope: 'Scorpio', colorName: 'Birch', hex: '#D2B48C', meaning: 'Fokus pada kehidupan & kematian.' },
  { month: 11, day: 10, horoscope: 'Scorpio', colorName: 'Tobacco Brown', hex: '#715E4C', meaning: 'Konsistensi mencapai obsesi.' },
  { month: 11, day: 11, horoscope: 'Scorpio', colorName: 'Pale Cream', hex: '#FFFDD0', meaning: 'Ketajaman mata detektif.' },
  { month: 11, day: 12, horoscope: 'Scorpio', colorName: 'Sand', hex: '#C2B280', meaning: 'Kemandirian sejati.' },
  { month: 11, day: 13, horoscope: 'Scorpio', colorName: 'Ash Gray', hex: '#B2BEB5', meaning: 'Strategi bertahan hidup.' },
  { month: 11, day: 14, horoscope: 'Scorpio', colorName: 'Gunmetal', hex: '#2A3439', meaning: 'Mental baja yang solid.' },
  { month: 11, day: 15, horoscope: 'Scorpio', colorName: 'Ink Black', hex: '#000000', meaning: 'Keheningan yang mematikan.' },
  { month: 11, day: 16, horoscope: 'Scorpio', colorName: 'Cherry Shell', hex: '#FBCCE7', meaning: 'Loyalitas tanpa batas.' },
  { month: 11, day: 17, horoscope: 'Scorpio', colorName: 'Orchid Pink', hex: '#F2BDCD', meaning: 'Perubahan nasib.' },
  { month: 11, day: 18, horoscope: 'Scorpio', colorName: 'Midnight Indigo', hex: '#4B0082', meaning: 'Misteri dan transformasi mendalam.' },
  { month: 11, day: 19, horoscope: 'Scorpio', colorName: 'Claret', hex: '#7F1734', meaning: 'Kekayaan batin yang tersembunyi.' },
  { month: 11, day: 20, horoscope: 'Scorpio', colorName: 'Dove Gray', hex: '#6D6C6C', meaning: 'Diam-diam mengamati.' },
  { month: 11, day: 21, horoscope: 'Scorpio', colorName: 'Pale Sallow', hex: '#C8B560', meaning: 'Kemampuan lahir kembali.' },
  { month: 11, day: 22, horoscope: 'Sagittarius', colorName: 'Matcha Green', hex: '#B2C248', meaning: 'Pandangan jauh ke depan.' },
  { month: 11, day: 23, horoscope: 'Sagittarius', colorName: 'Lye', hex: '#9E9764', meaning: 'Petualangan intelektual.' },
  { month: 11, day: 24, horoscope: 'Sagittarius', colorName: 'Lead', hex: '#7C7C7C', meaning: 'Filosofi dan pencarian makna.' },
  { month: 11, day: 25, horoscope: 'Sagittarius', colorName: 'Off Black', hex: '#313639', meaning: 'Kebebasan mutlak.' },
  { month: 11, day: 26, horoscope: 'Sagittarius', colorName: 'Pale Apricot', hex: '#FAD6A5', meaning: 'Antusiasme mencoba hal baru.' },
  { month: 11, day: 27, horoscope: 'Sagittarius', colorName: 'Skin Color', hex: '#FFCBA4', meaning: 'Keterbukaan terhadap budaya asing.' },
  { month: 11, day: 28, horoscope: 'Sagittarius', colorName: 'Suntan', hex: '#D2B48C', meaning: 'Cinta alam bebas.' },
  { month: 11, day: 29, horoscope: 'Sagittarius', colorName: 'Brick Red', hex: '#CB4154', meaning: 'Kejujuran tanpa filter.' },
  { month: 11, day: 30, horoscope: 'Sagittarius', colorName: 'Dead Leaf', hex: '#8A3324', meaning: 'Optimisme tanpa batas.' },

  // DESEMBER (Sagittarius & Capricorn) - Elemen Api & Tanah (Dari ekspansi kembali ke pembentukan struktur)
  { month: 12, day: 1, horoscope: 'Sagittarius', colorName: 'Flax', hex: '#EEDC82', meaning: 'Target besar dalam hidup.' },
  { month: 12, day: 2, horoscope: 'Sagittarius', colorName: 'Honey Suite', hex: '#D4AF37', meaning: 'Kebahagiaan dalam perjalanan.' },
  { month: 12, day: 3, horoscope: 'Sagittarius', colorName: 'Chestnut Plum', hex: '#852A2A', meaning: 'Sikap humoris dan santai.' },
  { month: 12, day: 4, horoscope: 'Sagittarius', colorName: 'Tawny Olive', hex: '#828B20', meaning: 'Kemandirian.' },
  { month: 12, day: 5, horoscope: 'Sagittarius', colorName: 'Adventurous Purple', hex: '#8E44AD', meaning: 'Eksplorasi dan kebebasan berpikir.' },
  { month: 12, day: 6, horoscope: 'Sagittarius', colorName: 'Citron Gray', hex: '#A4B1A0', meaning: 'Visi internasional.' },
  { month: 12, day: 7, horoscope: 'Sagittarius', colorName: 'Pale Limelight', hex: '#E6FF00', meaning: 'Pembelajaran tiada henti.' },
  { month: 12, day: 8, horoscope: 'Sagittarius', colorName: 'Rapeseed Oil', hex: '#A69220', meaning: 'Sikap toleran.' },
  { month: 12, day: 9, horoscope: 'Sagittarius', colorName: 'Oil Yellow', hex: '#FADA5E', meaning: 'Berpikir out-of-the-box.' },
  { month: 12, day: 10, horoscope: 'Sagittarius', colorName: 'Bronze', hex: '#CD7F32', meaning: 'Keyakinan pada diri sendiri.' },
  { month: 12, day: 11, horoscope: 'Sagittarius', colorName: 'Sea Shell Pink', hex: '#F0EAD6', meaning: 'Jiwa filantropi.' },
  { month: 12, day: 12, horoscope: 'Sagittarius', colorName: 'Salmon', hex: '#FA8072', meaning: 'Inspirasi memotivasi orang lain.' },
  { month: 12, day: 13, horoscope: 'Sagittarius', colorName: 'Washed Vermillion', hex: '#FF6347', meaning: 'Keberanian berpendapat.' },
  { month: 12, day: 14, horoscope: 'Sagittarius', colorName: 'Vermillion', hex: '#E34234', meaning: 'Antusiasme olahraga/fisik.' },
  { month: 12, day: 15, horoscope: 'Sagittarius', colorName: 'Burnt Orange', hex: '#CC5500', meaning: 'Visi idealis.' },
  { month: 12, day: 16, horoscope: 'Sagittarius', colorName: 'Beige White', hex: '#F5F5DC', meaning: 'Eksplorasi rohani.' },
  { month: 12, day: 17, horoscope: 'Sagittarius', colorName: 'Beige', hex: '#F5F5DC', meaning: 'Adaptasi mudah di mana saja.' },
  { month: 12, day: 18, horoscope: 'Sagittarius', colorName: 'Brown Gold', hex: '#A57164', meaning: 'Penjelajah sejati.' },
  { month: 12, day: 19, horoscope: 'Sagittarius', colorName: 'Candy Color', hex: '#E4A010', meaning: 'Kemurahan hati.' },
  { month: 12, day: 20, horoscope: 'Sagittarius', colorName: 'Heather', hex: '#9E7BB5', meaning: 'Rasa syukur dan kebebasan.' },
  { month: 12, day: 21, horoscope: 'Sagittarius', colorName: 'Lilac', hex: '#C8A2C8', meaning: 'Akhir petualangan sebagai awal baru.' },
  { month: 12, day: 22, horoscope: 'Capricorn', colorName: 'Heliotrope', hex: '#DF73FF', meaning: 'Fondasi tradisi yang kuat.' },
  { month: 12, day: 23, horoscope: 'Capricorn', colorName: 'Iris', hex: '#5A4FCF', meaning: 'Menghargai waktu.' },
  { month: 12, day: 24, horoscope: 'Capricorn', colorName: 'Eggplant', hex: '#614051', meaning: 'Tanggung jawab keluarga.' },
  { month: 12, day: 25, horoscope: 'Capricorn', colorName: 'Eggplant Blue', hex: '#311432', meaning: 'Fokus jangka panjang.' },
  { month: 12, day: 26, horoscope: 'Capricorn', colorName: 'Gold', hex: '#FFD700', meaning: 'Pencapaian status tertinggi.' },
  { month: 12, day: 27, horoscope: 'Capricorn', colorName: 'Sallow', hex: '#C8B560', meaning: 'Kesabaran mendaki puncak.' },
  { month: 12, day: 28, horoscope: 'Capricorn', colorName: 'Joan Miel', hex: '#FFC40C', meaning: 'Konservatif dan andal.' },
  { month: 12, day: 29, horoscope: 'Capricorn', colorName: 'Mustard', hex: '#FFDB58', meaning: 'Kekuatan disiplin.' },
  { month: 12, day: 30, horoscope: 'Capricorn', colorName: 'Autumn Leaf', hex: '#C15420', meaning: 'Kematangan visi.' },
  { month: 12, day: 31, horoscope: 'Capricorn', colorName: 'Turquoise Blue', hex: '#00FFEF', meaning: 'Penutupan siklus dan warisan abadi.' }
];